# Generated by Django 3.2 on 2023-08-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_Request',
            new_name='Service_requests',
        ),
        migrations.RenameModel(
            old_name='SupportRepresentative',
            new_name='Support_Representative',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='User',
        ),
    ]
